name: Compile and Release Executable

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compile Standalone Executable
        run: |
          python -m PyInstaller --noconsole --onefile --collect-all customtkinter --name hl-auto-clicker --icon=icon.ico main.py

      - name: Rename Executable for Release
        run: |
          mv dist/hl-auto-clicker.exe dist/HL-Auto-Clicker-Windows.exe

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/HL-Auto-Clicker-Windows.exe
          name: HL Auto Clicker ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
